frouriojs/create-frourio-app

.gitignore, CHANGELOG.md, package.json, server/templates/orm/prisma/server/prisma/.env, server/templates/orm/typeorm/server/.env, server/templates/server/.env
=> chore(release): 0.15.1

CHANGELOG.md, package.json, server/service/answers.ts
=> chore(release): 0.15.2

CHANGELOG.md, package.json
=> chore(release): 0.15.3

CHANGELOG.md, package.json, server/index.ts
=> chore(release): 0.15.4

CHANGELOG.md, package.json, server/index.ts
=> chore(release): 0.15.5

CHANGELOG.md, README.md, package.json, server/api/answers/controller.ts, server/index.ts, server/service/answers.ts
=> chore(release): 0.16.0

CHANGELOG.md, package.json, server/templates/server/service/tasks.ts
=> chore(release): 0.16.2

CHANGELOG.md, package.json, server/service/answers.ts
=> chore(release): 0.16.3

CHANGELOG.md, package.json, server/templates/aspida/nuxt/axios/nuxt.config.ts, server/templates/aspida/nuxt/fetch/nuxt.config.ts, server/templates/aspida/nuxt/fetch/package.json, server/templates/aspida/nuxt/fetch/plugins/api.ts
=> chore(release): 0.16.5

pages/index.tsx
On creating, the modal dialog below is displayed.
Isn't the word `tarminal` a typo of `terminal` ?
=> Fix typo: tarminal -> terminal

CHANGELOG.md, package.json, server/__test__/snapshot.md, server/__test__/snapshot.spec.ts, server/templates/client/sapper/tsconfig.json
=> chore(release): 0.19.1

CHANGELOG.md, package.json, server/api/dbConnection/controller.ts, server/service/answers.ts
=> chore(release): 0.21.2

.github/workflows/nodejs.yml, CHANGELOG.md, package.json, server/__test__/snapshot.md, server/templates/ci/actions/.github/workflows/nodejs.yml
=> chore(release): 0.22.1

components/main/index.tsx, components/question/index.tsx
closes https://github.com/frouriojs/create-frourio-app/issues/159
=> feat(react): show error line only after the input was touched

components/main/index.tsx, server/common/prompts.ts, server/utils/answers/random.ts
This should be merged after https://github.com/frouriojs/create-frourio-app/pull/168
resolves https://github.com/frouriojs/create-frourio-app/issues/160
=> fix: check whether the input is empty or not, and refactor

components/main/index.tsx, server/api/answers/controller.ts, server/api/hooks.ts, server/index.ts
closes https://github.com/frouriojs/create-frourio-app/issues/161
=> feat: open automatically dev client url after initialized

components/main/index.tsx, components/question/index.tsx, server/api/localPath/controller.ts, server/api/localPath/index.ts, server/service/answers.ts, server/service/localPath.ts
closes https://github.com/frouriojs/create-frourio-app/issues/170
=> feat: create only when target directory does not exist or empty

CHANGELOG.md, package.json, server/index.ts
=> chore(release): 0.26.1

CHANGELOG.md, package.json
=> chore(release): 0.26.2

server/service/generate.ts
closes https://github.com/frouriojs/create-frourio-app/issues/180
=> fix: decode as utf-8 only text files

server/templates/@client=sapper/package.json, server/templates/@client=sapper/src/client.ts, server/tests/generate.spec.ts
closes https://github.com/frouriojs/create-frourio-app/issues/179
=> fix: sapper typecheck and fix error

CHANGELOG.md, package.json, server/common/prompts.ts, server/pretense/package.json, server/pretense/yarn.lock, server/service/generate.ts, server/templates/@ci=actions/.github/workflows/@deployServer=pm2/deploy-server.yml, server/templates/@client=next/gitignore, server/templates/@client=nuxt/gitignore, server/templates/@client=sapper/gitignore, server/templates/@client=sapper/package.json, server/templates/@client=sapper/src/client.ts, server/templates/@daemon=pm2/ecosystem.config.js, server/templates/server/.env, server/templates/server/.env.example, server/templates/server/@orm=typeorm/.env, server/templates/server/@orm=typeorm/.env.example, server/templates/server/@orm=typeorm/service/envValues.ts, server/templates/server/@server=express/entrypoints/@orm=none/index.ts, server/templates/server/@server=express/entrypoints/@orm=prisma/index.ts, server/templates/server/@server=express/entrypoints/@orm=typeorm/index.ts, server/templates/server/@server=express/service/user.ts, server/templates/server/@server=fastify/entrypoints/@orm=none/index.ts, server/templates/server/@server=fastify/entrypoints/@orm=typeorm/index.ts, server/templates/server/@server=fastify/service/@orm=prisma/app.ts, server/templates/server/@server=fastify/service/user.ts, server/templates/server/service/envValues.ts, server/tests/generate.spec.ts, yarn.lock
=> chore(release): 0.26.3

CHANGELOG.md, package.json, server/api/dbConnection/controller.ts
=> chore(release): 0.26.4

server/templates/@testing=jest/@client=next/test/pages/index.test.tsx
closes https://github.com/frouriojs/create-frourio-app/issues/192
=> fix(template): refactor next pages test

package.json, server/api/dbConnection/controller.ts, server/common/prompts.ts, server/common/template-context.ts, server/index.ts, server/service/answers.ts, server/service/generate.ts, server/tests/generate.spec.ts, server/utils/answers/random.ts, server/utils/string/__tests__/index.spec.ts, server/utils/string/index.ts, tsconfig.json, yarn.lock
closes https://github.com/frouriojs/create-frourio-app/issues/183
=> feat: separate database info to save

server/pretense/package.json, server/pretense/yarn.lock, server/templates/@client=sapper/@dev-dep, server/templates/@client=sapper/rollup.config.js
Issue Number: closes https://github.com/frouriojs/create-frourio-app/issues/197
closes https://github.com/frouriojs/create-frourio-app/issues/197
=> fix(template): configure @rollup/plugin-json for sapper to build client successfully

.gitignore, CHANGELOG.md, jest.config.ts, package.json, server/api/dbConnection/controller.ts, server/common/prompts.ts, server/common/template-context.ts, server/index.ts, server/pretense/package.json, server/pretense/yarn.lock, server/service/answers.ts, server/service/generate.ts, server/templates/@client=sapper/@dev-dep, server/templates/@client=sapper/rollup.config.js, server/templates/@testing=jest/@client=next/@dev-dep, server/templates/@testing=jest/@client=next/test/pages/index.test.tsx, server/tests/generate.spec.ts, server/utils/answers/random.ts, server/utils/database/jest-context.ts, server/utils/string/__tests__/index.spec.ts, server/utils/string/index.ts, tsconfig.json, yarn.lock
=> chore(release): 0.27.0

components/main/index.tsx, server/api/answers/controller.ts
Issue Number: https://github.com/frouriojs/create-frourio-app/issues/190
絶対治るという程のものではないですが、安定すると思います。また、chrome のポップアップブロックにも阻まれなくなりました。
=> fix: open from server-side

server/service/getServerPort.ts
Issue Number: closes https://github.com/frouriojs/create-frourio-app/issues/213
=> fix: get random port for server from 10000-59999

server/templates/@client=next/package.json, server/templates/@client=nuxt/package.json, server/templates/@client=sapper/package.json, server/templates/server/package.json
Prismaを利用した際、手動でSQLを書き換えるケースが割とありそうなので、migrateに--create-onlyを付けたコマンドを追加しました。
Issue Number: https://github.com/frouriojs/create-frourio-app/issues/233
=> add command migrate:dev:createonly

server/templates/@ci=actions/.github/workflows/test.yml
cfaで生成したアプリ側のenvは`API_DATABASE_URL`を想定しているのに対して、Github Actionsのworkflowsでは`DATABASE_URL`でenvを指定していたため落ちていました。そのため、アプリ側のenv名に合わせるように修正しました。
Issue Number: https://github.com/frouriojs/create-frourio-app/issues/246
=> fix env name DATABASE_URL → API_DATABASE_URL

CHANGELOG.md, package.json, server/templates/@ci=actions/.github/workflows/test.yml, server/templates/@client=next/package.json, server/templates/@client=nuxt/package.json, server/templates/@client=sapper/package.json, server/templates/server/package.json, yarn.lock
=> chore(release): 0.28.2

server/common/prompts.ts
=> feat: change default pm value

server/api/answers/controller.ts, server/api/hooks.ts, server/index.ts, server/plugins/fastify-inject.ts, server/service/answers.ts
- resolves https://github.com/frouriojs/create-frourio-app/issues/308
- resolves #
Please upvode with reacting as :+1: to express your agreement.
=> fix: use positional arg for directory name

server/templates/@testing=jest/@client=next/test/pages/index.test.tsx
- resolves https://github.com/frouriojs/create-frourio-app/issues/310
- resolves #
- ...
Please upvode with reacting as :+1: to express your agreement.
=> fix nextjs frontend test for timing bugs

.github/dependabot.yml, .github/pull_request_template.md, .github/workflows/release-drafter-main.yml, server/templates/@testing=jest/@client=next/test/pages/index.test.tsx
- chore: typo
- ci: split release-drafter
- ci: dependabot
- fix: react hooks with none, and prevent double wrapping SWRConfig
CIの作業もしてたので少し入っている
=> fix: react hooks with none, and prevent double wrapping SWRConfig

package.json, server/api/dbConnection/controller.ts, server/index.ts, server/templates/@client=next/tsconfig.json, server/templates/@client=sapper/tsconfig.json, server/templates/server/tsconfig.json, yarn.lock
- resolves #
- resolves #
- CFAの外側のTypeScriptをv4.5にアップデート
- pathpida/aspida/frourioのアップデートに伴い、`perserveValueImports :false`を削除
- importのエラーを修正
- fastify-nextjsのエラーを修正
=> chore:Update TypeScript

.github/workflows/nodejs.yml
- resolves #
- resolves #
- ...
https://github.community/t/yarn-esockettimedout-on-windows/118776
=> ci: set timeout

.github/workflows/nodejs.yml
- resolves #
- resolves #
resolves https://github.com/frouriojs/create-frourio-app/issues/331
- ...
=> ci: set timeout for template test

CHANGELOG.md, server/service/answers.ts
- resolves #
- resolves #
- ...
=> fix: template path

package.json, server/index.ts, server/tests/generate.spec.ts
- resolves #
- resolves #
- ...
=> fix: fix how getting the version

components/main/index.tsx
> Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
- resolves #
- resolves #
- ...
=> fix: avoid creating websocket connection in client

server/pretense/package.json
- resolves #
- resolves #
- ...
=> fix: install typescript@4.7.4

CHANGELOG.md, package.json, server/pretense/package.json, server/templates/@client=next/tsconfig.json, yarn.lock
- resolves #
- resolves #
- ...
=> fix: update frourio@0.30.2

Makefile, server/index.ts
- resolves #
- resolves #
- ...
=> release v0.38.1

client/next.config.js, client/package.json
- resolves #
- resolves #
- ...
=> release v0.40.2

server/service/answers.ts
- resolves #
- resolves #
- ...
=> release v0.40.3

server/service/generate.ts, server/templates/client/@symlink=api, server/templates/client/@symlink=common, server/templates/client/api, server/templates/client/common
- resolves #
- resolves #
- ...
=> release v0.41.1
